openapi: 3.0.1
info:
  title: DASH API
  description: ''
  version: v1.0
servers:
  - url: https://dev-int-api-gateway.azure.defra.cloud/dash/v1.0
paths:
  '/openai/deployments/{deploymentmodel}/chat/completions':
    post:
      summary: Chat Completions
      description: 'Chat Completions '
      operationId: post
      parameters:
        - name: deploymentmodel
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
  /documentintelligence/documentModels/prebuilt-read:analyze:
    post:
      summary: Document Intelligence
      operationId: document-intelligence
      responses:
        '200':
          description: ''
components: { }
