openapi: 3.0.1
info:
  title: DASH API
  description: ''
  version: v1.0
servers:
  - url: https://dev-int-api-gateway.azure.defra.cloud/openai/deployments/v1.0
paths:
  /o4-mini/chat/completions:
    post:
      summary: O4 MINI
      description: O4 MINI
      operationId: post
      responses:
        '200':
          description: ''
components: { }
